// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzqgEC2K7teYRsUpw5NMECQTJg3Afnnj0',
    appId: '1:645063695535:web:3baa059a0853c6e262c85a',
    messagingSenderId: '645063695535',
    projectId: 'quickpm-8f9c9',
    authDomain: 'quickpm-8f9c9.firebaseapp.com',
    storageBucket: 'quickpm-8f9c9.firebasestorage.app',
    measurementId: 'G-R19RZYENY9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEel3CbUOOl2ViY5AYjPD-lphtmalgpyc',
    appId: '1:645063695535:ios:eac242a8a98e924062c85a',
    messagingSenderId: '645063695535',
    projectId: 'quickpm-8f9c9',
    storageBucket: 'quickpm-8f9c9.firebasestorage.app',
    iosClientId: '645063695535-qlvij3ld97okog0fqf3noa7ur0jbhht4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickPm',
  );

}