// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCShg0IQ1HyJHsi2sqfQRmAiDZFnjwOI0',
    appId: '1:963685034908:web:d3a8f342f88f5fd4763659',
    messagingSenderId: '963685034908',
    projectId: 'reado-c8d21',
    authDomain: 'reado-c8d21.firebaseapp.com',
    storageBucket: 'reado-c8d21.firebasestorage.app',
    measurementId: 'G-WNQG721JGL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcpcBHeYi0r-m5HwL7_WYPR4rVmGB6UWk',
    appId: '1:963685034908:ios:540d02681ce7ab84763659',
    messagingSenderId: '963685034908',
    projectId: 'reado-c8d21',
    storageBucket: 'reado-c8d21.firebasestorage.app',
    iosBundleId: 'com.example.quickPm',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkGuAPRKM9QeTeQ3agbvTUNSmtb7QNh1c',
    appId: '1:963685034908:android:7aabe607ee1d6107763659',
    messagingSenderId: '963685034908',
    projectId: 'reado-c8d21',
    storageBucket: 'reado-c8d21.firebasestorage.app',
  );

}